[package]
name = "nn"
version = "0.1.0"
authors = ["planet0104 <planet0104@gmail.com>"]

[dependencies]
rand = "*"
scraper = "0.7.0"
serde_json = "1.0"

[dependencies.sdl2]
version = "0.31.0"
features = ["bundled", "static-link", "gfx"]